# Remove tls properties from registry
- type: remove
  path: /instance_groups/name=registry/jobs/name=registry/properties/http/tls

# Add external URL property to registry
- type: replace
  path: /instance_groups/name=registry/jobs/name=registry/properties/http/host?
  value: https://registry.((system_domain))

# Add route registrar job
- type: replace
  path: /instance_groups/name=registry/jobs/-
  value:
    name: route_registrar
    release: routing
    consumes:
      nats:
        from: nats
        deployment: cf
    properties:
      route_registrar:
        routes:
          - name: registry
            registration_interval: 20s
            port: 5000
            uris:
              - registry.((system_domain))

# Add routing release
- type: replace
  path: /releases/-
  value:
    name: routing
    version: 0.159.0
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/cf-routing-release?v=0.159.0
    sha1: 739f663f976fea826595880cfd58470bc8d49172
