# Enable Swift storage backend
- type: replace
  path: /instance_groups/name=registry/jobs/name=registry/properties/storage/driver?
  value: swift

# Add Swift properties
- type: replace
  path: /instance_groups/name=registry/jobs/name=registry/properties/storage/swift?
  value:
    username: ((registry_storage_swift_username))
    password: ((registry_storage_swift_password))
    auth_url: ((registry_storage_swift_auth_url))
    container: ((registry_storage_swift_container))
